#!groovy

// Generated by IBM TransformationAdvisor
// Wed Sep 19 19:49:06 UTC 2018

@Library('MicroserviceBuilder') _
microserviceBuilderPipeline {
    image = 'modresortswar'
    mvnCommands = '--version'
    test='false'
}